"VIMIDE vimrc basic settings
"--------start---------
set fileencodings=utf-8,cp936,ucs-bom,gbk
set helplang=cn

"ColorScheme
colorscheme desert

set shiftwidth=2
set tabstop=2
set expandtab
set nobackup
set noswapfile
set nowb
set backspace=start,indent,eol
set nu
set autoindent
set smartindent
set wrap
set mouse=a

set noerrorbells
set novisualbell

syntax on

filetype plugin on
filetype indent on

set completeopt=longest,menu
"自动补全命令时候使用菜单式匹配列表  
set wildmenu
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType java set omnifunc=javacomplete#Complet

"Pydiction
let g:pydiction_location = 'D:\Program Files\Vim\vim73\ftplugin\complete-dict'


map <C-w> :NERDTree<cr>
map <C-t> :TlistToggle<cr>
vmap <C-c> "+y

let Tlist_Ctags_Cmd='ctags.exe'
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow=1
"tags
set tags=C:\Users\lusky\quantum


let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplModSelTarget = 1

inoremap <C-P> <ESC>:call PhpDocSingle()<CR>i 
nnoremap <C-P> :call PhpDocSingle()<CR> 
vnoremap <C-P> :call PhpDocRange()<CR> 
"--------end--------
